First cut at i2c support - it compiles, but fails at runtime ("bad" scl gpio)
The esp_idf driver implementation complains about the gpio we're using for
SCL (the "i2c_init(): 0N" are breadcrumbs in my i2c initialization
routine).

Others on the esp32 forums have complained about i2c SCL and SDA
assignments other than those used in the esp_idf sdk examples failing for
apparently arbitrary reasons - need to look into this.

\_\_\_\_ \_\_\_\_ \_\_\_\_ \_\_\_\_ \_\_\_\_ \_\_\_\_ \_\_\_\_ \_\_\_\_
i2c_init(): 01 I2C_SDA is GPIO 23, and I2C_SCL is GPIO 24.
i2c_init(): 02
E (248) i2c: /Users/vincecotter/Documents/work/currant/TASKS/TASK020_ESP32/esp32sdk/gits/esp-idf/components/driver/i2c.c:827 (i2c_set_pin):scl gpio number error
i2c_init(): 03
i2c_init(): 04
E (258) i2c: /Users/vincecotter/Documents/work/currant/TASKS/TASK020_ESP32/esp32sdk/gits/esp-idf/components/driver/i2c.c:1207 (i2c_master_cmd_begin):i2c driver not installed
error: can't set s5852 pointer!
i2c_init(): 05
\_\_\_\_ \_\_\_\_ \_\_\_\_ \_\_\_\_ \_\_\_\_ \_\_\_\_ \_\_\_\_ \_\_\_\_